oauth2:
  client:
    registration:
      github:
        client-id: ${GITHUB_OAUTH_CLIENT_ID}
        client-secret: ${GITHUB_OAUTH_CLIENT_SECRET}
      google:
        client-id: ${GOOGLE_OAUTH_CLIENT_ID}
        client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET}
